import { ArticleProps } from "@/types/interfaces";

export const blogPosts: ArticleProps[] = [
    {
        id: 1,
        title: "How I Overcome Creative Blocks as a Creative Developer",
        slug: "how-i-overcome-creative-blocks",
        published_date: "2024-10-01",
        excerpt: "Discover my personal techniques for breaking through creative blocks and staying inspired as a developer in the creative industry.",
        featured: true,
        featuredImgUrl: "/assets/images/blog/thumbnails/3.jpg",
        categories: ["Productivity", "Inspiration"],
        tags: ["creative blocks", "motivation", "developer journey"],
        status: "published",
        content: "In this post, I share my strategies for overcoming creative blocks...",
        parent_post: null,
        related_posts: [2, 3],
    },
    {
        id: 2,
        title: "How to Run Different Versions of Angular on Your Windows Machine",
        slug: "run-different-versions-angular-windows",
        published_date: "2024-09-15",
        excerpt: "Learn step-by-step how to set up multiple Angular versions on a Windows machine, making development smoother across projects.",
        featured: true,
        featuredImgUrl: "/assets/images/blog/thumbnails/1.jpg",
        categories: ["Development", "Angular", "Tutorial"],
        tags: ["Angular", "Windows", "setup", "multi-version"],
        status: "published",
        content: "Running multiple Angular versions can be crucial for supporting different projects...",
        parent_post: null,
        related_posts: [1, 3],
    },
    {
        id: 3,
        title: "10 Free VSCode Extensions to Supercharge Your Productivity as a Developer",
        slug: "10-free-vscode-extensions",
        published_date: "2024-08-20",
        excerpt: "Boost your development workflow with these 10 essential VSCode extensions that I rely on every day for productivity.",
        featured: true,
        featuredImgUrl: "/assets/images/blog/thumbnails/2.jpg",
        categories: ["Productivity", "Tools", "VSCode"],
        tags: ["VSCode", "extensions", "productivity", "developer tools"],
        status: "published",
        content: "In this article, we explore my top VSCode extensions for boosting productivity...",
        parent_post: null,
        related_posts: [1, 2],
    },
    {
        id: 4,
        title: "10 Free Websites to Discover Hidden Treasures for Your Development Journey",
        slug: "10-free-websites-for-developers",
        published_date: "2024-07-30",
        excerpt: "Explore 10 valuable websites that offer resources, tips, and tools to support and enrich your path as a developer.",
        featured: false,
        featuredImgUrl: "/assets/images/blog/thumbnails/4.jpg",
        categories: ["Resources", "Development"],
        tags: ["free resources", "websites", "developer resources"],
        status: "published",
        content: "Here’s a list of hidden gem websites that can provide invaluable resources for developers...",
        parent_post: null,
        related_posts: [3, 5],
    },
    {
        id: 5,
        title: "Accessibility Guide 1: Creating Custom Accordions Using HTML5",
        slug: "accessibility-guide-creating-custom-accordions",
        published_date: "2024-11-10",
        excerpt: "An in-depth guide on creating accessible, custom accordions in HTML5 for an inclusive user experience.",
        featured: false,
        featuredImgUrl: "/assets/images/blog/thumbnails/5.jpg",
        categories: ["Accessibility", "HTML5", "Frontend"],
        tags: ["accessibility", "accordion", "HTML5"],
        status: "draft",
        content: "This guide walks you through creating accessible accordions using semantic HTML5 elements...",
        parent_post: null,
        related_posts: [6],
    },
    {
        id: 6,
        title: "Accessibility Guide 2: Creating Custom Select Menus Using HTML5",
        slug: "accessibility-guide-creating-custom-select",
        published_date: "2024-11-15",
        excerpt: "Learn how to create accessible custom select menus in HTML5 that work for all users, including those with disabilities.",
        featured: false,
        featuredImgUrl: "/assets/images/blog/thumbnails/6.jpg",
        categories: ["Accessibility", "HTML5", "Frontend"],
        tags: ["accessibility", "select menu", "HTML5"],
        status: "draft",
        content: "Building accessible select menus can enhance usability and inclusivity in web applications...",
        parent_post: 5,
        related_posts: [5],
    },
    {
        id: 7,
        title: "10 Free Chrome Extensions That Will 10X Your Productivity as a Developer",
        slug: "10-free-chrome-extensions-for-developers",
        published_date: "2024-10-05",
        excerpt: "Discover 10 powerful Chrome extensions that every developer should know about to streamline their workflow.",
        featured: true,
        featuredImgUrl: "",
        categories: ["Productivity", "Tools", "Chrome Extensions"],
        tags: ["Chrome", "extensions", "productivity", "developer tools"],
        status: "published",
        content: "This article introduces some must-have Chrome extensions that can boost productivity and efficiency...",
        parent_post: null,
        related_posts: [3],
    },
    // Additional suggested articles
    {
        id: 8,
        title: "Mastering CSS Flexbox: A Complete Guide",
        slug: "mastering-css-flexbox-guide",
        published_date: "2024-10-20",
        excerpt: "A comprehensive guide to mastering CSS Flexbox, one of the most powerful layout systems in modern web design.",
        featured: false,
        featuredImgUrl: "",
        categories: ["CSS", "Frontend"],
        tags: ["CSS", "Flexbox", "layout", "web design"],
        status: "published",
        content: "Flexbox is a powerful tool in CSS for building responsive layouts...",
        parent_post: null,
        related_posts: [],
    },
    {
        id: 9,
        title: "Getting Started with TypeScript for JavaScript Developers",
        slug: "getting-started-with-typescript",
        published_date: "2024-09-10",
        excerpt: "An introductory guide to help JavaScript developers get up and running with TypeScript.",
        featured: false,
        featuredImgUrl: "",
        categories: ["JavaScript", "TypeScript", "Development"],
        tags: ["TypeScript", "JavaScript", "tutorial"],
        status: "published",
        content: "TypeScript is a popular superset of JavaScript that brings static typing to the language...",
        parent_post: null,
        related_posts: [],
    },
    {
        id: 10,
        title: "Understanding the Basics of React Hooks",
        slug: "understanding-react-hooks-basics",
        published_date: "2024-08-25",
        excerpt: "A beginner's guide to understanding and using React Hooks in functional components.",
        featured: true,
        featuredImgUrl: "",
        categories: ["React", "JavaScript", "Frontend"],
        tags: ["React", "hooks", "frontend development"],
        status: "published",
        content: "React Hooks are a powerful addition to functional components, enabling developers to use state and lifecycle features...",
        parent_post: null,
        related_posts: [9],
    },
];